# Generated by Django 5.0.3 on 2024-05-03 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta', models.CharField(max_length=30)),
                ('data_caducitat', models.CharField(max_length=30)),
                ('cvc', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuari.usuari')),
            ],
        ),
    ]
