# Generated by Django 5.0.3 on 2024-04-12 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('gama', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cataleg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataleg.producte')),
            ],
        ),
    ]
