# Generated by Django 5.0.3 on 2024-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataleg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='estoc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producte',
            name='pes',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producte',
            name='preu',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
