# Generated by Django 5.0.3 on 2024-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataleg', '0002_producte_estoc_producte_pes_producte_preu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataleg',
            name='id_producte',
        ),
        migrations.AddField(
            model_name='cataleg',
            name='productes',
            field=models.ManyToManyField(to='cataleg.producte'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='estoc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producte',
            name='pes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producte',
            name='preu',
            field=models.FloatField(default=0),
        ),
    ]
