version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db_m07_uf4_p5
    environment:
      - POSTGRES_DB=ITIC_DB
      - POSTGRES_PASSWORD=ITIC
      - POSTGRES_USER=ITIC_user
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_m07_uf4_p5
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: system@gmail.com
      PGADMIN_DEFAULT_PASSWORD: system
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: