# Generated by Django 4.1.6 on 2024-05-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0001_initial'),
        ('usuari', '0001_initial'),
        ('comandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandes',
            name='carreto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carreto.carreto'),
        ),
        migrations.AddField(
            model_name='comandes',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuari.usuari'),
        ),
    ]
